defaults:
  - _self_ # controls the merge order so MUST come first (base.yaml's keys take priority, so its use_gaze: False default will be overridden by the loss config's use_gaze: True)
  - model: vit_s_14
  - loss: ce
  - optional reg_loss_fn: null

seed: 42
patch_size: 14

trainer:
  optimizer:
    _target_: torch.optim.AdamW
    _partial_: true
    lr: 0.01
    weight_decay: 0.01

  scheduler:
    _target_: torch.optim.lr_scheduler.CosineAnnealingLR
    _partial_: true
    T_max: ${trainer.training.num_epochs}
    eta_min: 1.0e-6

  training:
    num_epochs: 5

data_pipeline:
  dataloader:
    batch_size: 64
    num_workers: 4

  train_test_split:
    test_size: 0.2
    random_state: ${seed}

  load_dataset:
    _target_: GABRIL_utils.utils.load_dataset
    env: Seaquest
    seed: ${seed}
    datapath: 'dataset/'
    conf_type: normal
    conf_randomness: 0.0
    stack: 1
    num_episodes: 20
    use_gaze: False
    data_source: Our
    gaze_mask_sigma: 15.0
    gaze_mask_coef: 0.7
